package com.mycompany.trabalho_analisador_sintatico_artur_pedro_ryudi;/* Generated By:JavaCC: Do not edit this line. Analisador_semantico.java */

import java.util.ArrayList;

public class Analisador_semantico implements Analisador_sintaticoConstants {
    public static void main(String[] Args)
    {
        Analisador_semantico analisador2 = new Analisador_semantico(System.in);
        analisador2.Analisador_semantico();
    }
  
  private String erroSemantico = "";

  public String getErroSemantico() {
    return erroSemantico;
  }

  public void setErroSemantico(String erroSemantico) {
    this.erroSemantico = erroSemantico;
  }

  private String contexto;
  

  public int getPonteiro() {
    return ponteiro;
  }

  public void setPonteiro(int ponteiro) {
    this.ponteiro = ponteiro;
  }

  private int vt, vp, tipo, ponteiro = 1;

  public String getContexto() {
    return contexto;
  }

  public void setContexto(String contexto) {
    this.contexto = contexto;
  }

  public int getVt() {
    return vt;
  }

  public void setVt(int vt) {
    this.vt = vt;
  }

  public int getVp() {
    return vp;
  }

  public void setVp(int vp) {
    this.vp = vp;
  }

  public int getTipo() {
    return tipo;
  }

  public void setTipo(int tipo) {
    this.tipo = tipo;
  }

  private ArrayList<Instrucao> AreaInstrucoes = new ArrayList<>();

  public void addAreaInstrucoes(int numero, String codigo, String param){
      AreaInstrucoes.add(new Instrucao(numero,codigo,param));
  }

  public Instrucao getInstrucaoAreaInstrucoes(int endereco){
    for(Instrucao i: AreaInstrucoes){
      if(i.getNumero() == endereco)
        return i;
    }
    return null;
    //Erro
  }

  public ArrayList<Instrucao> getAreaInstrucoes(){
    return this.AreaInstrucoes;
  }
  
  public void resetAreaInstrucoes(){
      AreaInstrucoes.clear();
  }

  private ArrayList<Simbolo> TabelaSimbolos = new ArrayList<>();

  public boolean existTabelaSimbolos(String identificador){
      for(Simbolo s: TabelaSimbolos){
        if(s.getNome().equals(identificador))
          return true;
      }
      return false;
  }
  
  public void printTabelaSimbolos(){
      for(Simbolo s: TabelaSimbolos){
            System.out.println("chegou no print");
            System.out.println(s);
      }
  }
  public Simbolo getKeySimbolTabelaSimbolos(String chave){
    for (Simbolo s:TabelaSimbolos){
      if(s.getNome().equals(chave))
        return s;
    }
    return null; // erro
  }

  public void addtabelaSimbolos(String nome, String categoria,int atributo){
    TabelaSimbolos.add(new Simbolo(nome,categoria,atributo));
  }

  private ArrayList<Integer> pilhaDesvios = new ArrayList<>();

  public ArrayList<Integer> getPilhaDesvios(){
    return this.pilhaDesvios;
  }

  public void empilharDesvios(int dado){
    this.pilhaDesvios.add(dado);
  }

  public int desempilharPilhaDesvios(){
    int ultimoIndice = pilhaDesvios.size() - 1;
    int ultimoValor = pilhaDesvios.get(ultimoIndice);
    pilhaDesvios.remove(ultimoIndice);

    return ultimoValor;
  }

  final public void Analisador_semantico() {
    try{
      jj_consume_token(MAKE);
      IdentificadorPrograma();
      DecConstVar();
      ListaComandos();
      jj_consume_token(END);
      jj_consume_token(PONTO);
      Ações.acao1(this);
      jj_consume_token(0);
    }
    catch(ParseException e){
    }
  }

  final public void IdentificadorPrograma() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      jj_consume_token(IDENTIFICADOR);
      Ações.acao2(this);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
  }

  final public void DecConstVar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONST:
      DecConst();
      Variaveis3();
      break;
    case VAR:
      DecVar();
      Constantes3();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
        
    }
  }

  final public void DecConst() throws ParseException {
    jj_consume_token(CONST);
    Ações.acao3(this);
    Constantes();
    jj_consume_token(END);
    jj_consume_token(PONTO_E_VIRGULA);
  }

  final public void Constantes() throws ParseException {
    Tipo();
    jj_consume_token(DOIS_PONTOS);
    ListaIdent();
    Ações.acao4(this);
    jj_consume_token(IGUAL);
    Valor();
    Ações.acao5(this);
    jj_consume_token(PONTO);
    Constantes2();
  }

  final public void Valor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONSTANTES_INT:
      jj_consume_token(CONSTANTES_INT);
      break;
    case CONSTANTES_FLOAT:
      jj_consume_token(CONSTANTES_FLOAT);
      break;
    case CONSTANTE_LITARAL_APOSTROFO:
      jj_consume_token(CONSTANTE_LITARAL_APOSTROFO);
      break;
    case CONSTANTE_LITARAL_ASPAS:
      jj_consume_token(CONSTANTE_LITARAL_ASPAS);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Constantes2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case REAL:
    case CHAR:
    case BOOL:
      Constantes();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
  }

  final public void Constantes3() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONST:
      DecConst();
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
  }

  final public void DecVar() throws ParseException {
      jj_consume_token(VAR);
      Ações.acao6(this);
      Variaveis();
      jj_consume_token(END);
      jj_consume_token(PONTO_E_VIRGULA);
  }

  final public void Variaveis() throws ParseException {
    Tipo();
    jj_consume_token(DOIS_PONTOS);
    ListaIdent();
    Ações.acao4(this);
    jj_consume_token(PONTO);
    Variaveis2();
  }

  final public void Variaveis2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case REAL:
    case CHAR:
    case BOOL:
      Variaveis();
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
  }

  final public void Variaveis3() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VAR:
      DecVar();
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
  }

  final public void Tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
      jj_consume_token(INT);
      Ações.acao7(this);
      break;
    case REAL:
      jj_consume_token(REAL);
      Ações.acao8(this);
      break;
    case CHAR:
      jj_consume_token(CHAR);
      Ações.acao9(this);
      break;
    case BOOL:
      jj_consume_token(BOOL);
      Ações.acao10(this);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void ListaIdent() throws ParseException {
    jj_consume_token(IDENTIFICADOR);
    Ações.acao11(this);
    ListaIdent2();
  }

  final public void ListaIdent2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VIRGULA:
      jj_consume_token(VIRGULA);
      ListaIdent();
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
  }

  final public void ListaComandos() throws ParseException {
    Comando();
    jj_consume_token(PONTO);
    ListaComandos2();
  }

  final public void ListaComandos2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GET:
    case PUT:
    case IF:
    case TRUE:
    case FALSE:
    case WHILE:
    case ABRE_PARENTESES:
    case EXCLAMACAO:
    case IDENTIFICADOR:
    case CONSTANTES_INT:
    case CONSTANTES_FLOAT:
    case CONSTANTE_LITARAL_ASPAS:
    case CONSTANTE_LITARAL_APOSTROFO:
      ListaComandos();
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
  }

  final public void Comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TRUE:
    case FALSE:
    case ABRE_PARENTESES:
    case EXCLAMACAO:
    case IDENTIFICADOR:
    case CONSTANTES_INT:
    case CONSTANTES_FLOAT:
    case CONSTANTE_LITARAL_ASPAS:
    case CONSTANTE_LITARAL_APOSTROFO:
      Atribuicao();
      break;
    case GET:
      Entrada();
      break;
    case PUT:
      Saida();
      break;
    case IF:
      Selecao();
      break;
    case WHILE:
      Repeticao();
      break;
    default:
      jj_la1[10] = jj_gen;
        jj_consume_token(-1);
    }
  }

  final public void Atribuicao() throws ParseException {
      Expressao();
      jj_consume_token(ATRIBUICAO);
      jj_consume_token(IDENTIFICADOR);
      Ações.acao12(this);
  }

  final public void Entrada() throws ParseException {
      jj_consume_token(GET);
      Ações.acao13(this);
      jj_consume_token(ABRE_PARENTESES);
      ListaIdent();
      jj_consume_token(FECHA_PARENTESES);
  }

  final public void Saida() throws ParseException {
    jj_consume_token(PUT);
    jj_consume_token(ABRE_PARENTESES);
    ListaIdentConst();
    jj_consume_token(FECHA_PARENTESES);
  }

  final public void ListaIdentConst() throws ParseException {
    Item();
    Ações.acao14(this);
    ListaIdentConst2();
  }

  final public void ListaIdentConst2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VIRGULA:
      jj_consume_token(VIRGULA);
      ListaIdentConst();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
  }

  final public void Item() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      jj_consume_token(IDENTIFICADOR);
      Ações.acao15(this);
      break;
    case CONSTANTES_INT:
      jj_consume_token(CONSTANTES_INT);
      Ações.acao16(this);
      break;
    case CONSTANTES_FLOAT:
      jj_consume_token(CONSTANTES_FLOAT);
      Ações.acao17(this);
      break;
    case CONSTANTE_LITARAL_ASPAS:
      jj_consume_token(CONSTANTE_LITARAL_ASPAS);
      Ações.acao18(this);
      break;
    case CONSTANTE_LITARAL_APOSTROFO:
      jj_consume_token(CONSTANTE_LITARAL_APOSTROFO);
      Ações.acao18(this);
      break;
    case TRUE:
      jj_consume_token(TRUE);
      Ações.acao19(this);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      Ações.acao20(this);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void Selecao() throws ParseException {
    jj_consume_token(IF);
    Expressao();
    Ações.acao21(this);
    jj_consume_token(THEN);
    ListaComandos();
    Senao();
    jj_consume_token(END);
    Ações.acao22(this);
  }

  final public void Senao() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      Ações.acao23(this);
      ListaComandos();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  final public void Repeticao() throws ParseException {
    jj_consume_token(WHILE);
    Ações.acao24(this);
    Expressao();
    Ações.acao25(this);
    jj_consume_token(DO);
    ListaComandos();
    jj_consume_token(END);
    Ações.acao26(this);
  }

  final public void Expressao() throws ParseException {
    ExpressaoAritLog();
    Expressao2();
  }

  final public void Expressao2() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IGUAL:
    case DIFERENTE:
    case MENOR:
    case MAIOR:
    case MENOR_IGUAL:
    case MAIOR_IGUAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IGUAL:
        jj_consume_token(IGUAL);
        ExpressaoAritLog();
        Ações.acao27(this);
        break;
      case DIFERENTE:
        jj_consume_token(DIFERENTE);
        ExpressaoAritLog();
        Ações.acao28(this);
        break;
      case MENOR:
        jj_consume_token(MENOR);
        ExpressaoAritLog();
        Ações.acao29(this);
        break;
      case MAIOR:
        jj_consume_token(MAIOR);
        ExpressaoAritLog();
        Ações.acao30(this);
        break;
      case MAIOR_IGUAL:
        jj_consume_token(MAIOR_IGUAL);
        ExpressaoAritLog();
        Ações.acao32(this);
        break;
      case MENOR_IGUAL:
        jj_consume_token(MENOR_IGUAL);
        ExpressaoAritLog();
        Ações.acao31(this);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[15] = jj_gen;
      ;
    }
  }

  final public void ExpressaoAritLog() throws ParseException {
    Termo2();
    MenorPri();
  }

  final public void MenorPri() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MAIS:
    case MENOS:
    case BARRA_VERTICAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MAIS:
        jj_consume_token(MAIS);
        Termo2();
        Ações.acao33(this);
        MenorPri();
        break;
      case MENOS:
        jj_consume_token(MENOS);
        Termo2();
        Ações.acao34(this);
        MenorPri();
        break;
      case BARRA_VERTICAL:
        jj_consume_token(BARRA_VERTICAL);
        Termo2();
        Ações.acao35(this);
        MenorPri();
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
  }

  final public void Termo2() throws ParseException {
    Termo();
    MediaPri();
  }

  final public void MediaPri() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MULTIPLICACAO:
    case DIVISAO:
    case DIVISAO_INTEIRA:
    case RESTO_DIVISAO_INTEIRA:
    case E_COMERCIAL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLICACAO:
        jj_consume_token(MULTIPLICACAO);
        Termo();
        Ações.acao36(this);
        MediaPri();
        break;
      case DIVISAO:
        jj_consume_token(DIVISAO);
        Termo();
        Ações.acao37(this);
        MediaPri();
        break;
      case DIVISAO_INTEIRA:
        jj_consume_token(DIVISAO_INTEIRA);
        Termo();
        Ações.acao38(this);
        MediaPri();
        break;
      case RESTO_DIVISAO_INTEIRA:
        jj_consume_token(RESTO_DIVISAO_INTEIRA);
        Termo();
        Ações.acao39(this);
        MediaPri();
        break;
      case E_COMERCIAL:
        jj_consume_token(E_COMERCIAL);
        Termo();
        Ações.acao40(this);
        MediaPri();
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
  }

  final public void Termo() throws ParseException {
    Elemento();
    MaiorPri();
  }

  final public void MaiorPri() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EXPONENCIAL:
      jj_consume_token(EXPONENCIAL);
      Elemento();
      Ações.acao41(this);
      MaiorPri();
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  final public void Elemento() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFICADOR:
      jj_consume_token(IDENTIFICADOR);
      Ações.acao15(this);
      break;
    case CONSTANTE_LITARAL_APOSTROFO:
      jj_consume_token(CONSTANTE_LITARAL_APOSTROFO);
      Ações.acao18(this);
      break;
    case CONSTANTE_LITARAL_ASPAS:
      jj_consume_token(CONSTANTE_LITARAL_ASPAS);
      Ações.acao18(this);
      break;
    case CONSTANTES_INT:
      jj_consume_token(CONSTANTES_INT);
      Ações.acao16(this);
      break;
    case CONSTANTES_FLOAT:
      jj_consume_token(CONSTANTES_FLOAT);
      Ações.acao17(this);
      break;
    case TRUE:
      jj_consume_token(TRUE);
      Ações.acao19(this);
      break;
    case FALSE:
      jj_consume_token(FALSE);
      Ações.acao20(this);
      break;
    case ABRE_PARENTESES:
      jj_consume_token(ABRE_PARENTESES);
      Expressao();
      jj_consume_token(FECHA_PARENTESES);
      break;
    case EXCLAMACAO:
      jj_consume_token(EXCLAMACAO);
      jj_consume_token(ABRE_PARENTESES);
      Expressao();
      jj_consume_token(FECHA_PARENTESES);
      Ações.acao42(this);
      break;
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  /** Generated Token Manager. */
  public Analisador_sintaticoTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;

  public String getCurrentTokenImage() {
    return token.image;
  }

  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[22];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x600,0x0,0xf0000,0x200,0xf0000,0x400,0xf0000,0x10000000,0x20b03800,0x20b03800,0x10000000,0x300000,0x4000,0x0,0x0,0x80000000,0x80000000,0x0,0x0,0x0,0x20300000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x8000,0x0,0xf0000,0x0,0x0,0x0,0x0,0x0,0x0,0xfc000,0xfc000,0x0,0xf8000,0x0,0xfc0,0xfc0,0x2001,0x2001,0x1036,0x1036,0x8,0xfc000,};
   }

  /** Constructor with InputStream. */
  public Analisador_semantico(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Analisador_semantico(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Analisador_sintaticoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Analisador_semantico(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Analisador_sintaticoTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Analisador_semantico(Analisador_sintaticoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Analisador_sintaticoTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 22; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[52];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 22; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 52; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
