package com.mycompany.trabalho_analisador_sintatico_artur_pedro_ryudi;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Bebeto
 */
public class Tela_Salvar extends javax.swing.JDialog {

    private String painelTextSaved;

    private String pathSaved;

    private Tela2 pai;

    public String getPainelTextSaved() {
        return painelTextSaved;
    }

    private File file;

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }

    public void setPainelTextSaved(String painelTextSaved) {
        this.painelTextSaved = painelTextSaved;
    }

    public Tela_Salvar(java.awt.Frame parent, boolean modal, String painelTextSaved, Tela2 pai) {
        super(parent, modal);
        this.pathSaved = pathSaved;
        this.pai = pai;
        initComponents();
        this.setPainelTextSaved(painelTextSaved);
        this.setLocationRelativeTo(null);
        this.setTitle("Salvar Arquivo");
        this.setVisible(true);
    }
    public int getSalvar(){
        return salvar;
    }
    
    private int salvar;
    private int select = 0;

    public int getSelect() {
        return select;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        simTelaSalvar = new javax.swing.JButton();
        naoTelaSalvar = new javax.swing.JButton();
        cancelarTelaSalvar = new javax.swing.JButton();
        textoTelaSalvar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        simTelaSalvar.setText("Sim");
        simTelaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simTelaSalvarActionPerformed(evt);
            }
        });

        naoTelaSalvar.setText("Não");
        naoTelaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoTelaSalvarActionPerformed(evt);
            }
        });

        cancelarTelaSalvar.setText("Cancelar");
        cancelarTelaSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTelaSalvarActionPerformed(evt);
            }
        });

        textoTelaSalvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTelaSalvar.setText("Deseja salvar o arquivo?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(simTelaSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(naoTelaSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelarTelaSalvar)
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoTelaSalvar)
                .addGap(107, 107, 107))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(textoTelaSalvar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simTelaSalvar)
                    .addComponent(naoTelaSalvar)
                    .addComponent(cancelarTelaSalvar))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private File simTelaSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        salvar = 0;
        super.getParent().setEnabled(true);
        super.getParent().setFocusable(true);
        this.dispose();

        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de Texto (.txt)", "txt");
        fc.setFileFilter(filter);
        int res = fc.showSaveDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            pathSaved = arquivo.getPath();
            pai.setPathSaved(pathSaved);
            String filepath = arquivo.getPath();
            // Verifica se o arquivo tem a extensão .txt; se não, adiciona
            if (!filepath.toLowerCase().endsWith(".txt")) {
                arquivo = new File(filepath + ".txt");
            }

            // Se o arquivo já existe, perguntar se deseja sobrescrevê-lo
            if (arquivo.exists()) {
                int resposta = JOptionPane.showConfirmDialog(this,
                        "O arquivo já existe. Deseja sobrescrevê-lo?",
                        "Confirmar Sobrescrita",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE);

                if (resposta == JOptionPane.NO_OPTION) {
                    return null; // Se o usuário escolher "Não", retorna sem salvar
                }
            }
            this.setFile(arquivo); // Atualiza a referência ao arquivo

            try (FileWriter writer = new FileWriter(arquivo)) {
                String texto = this.getPainelTextSaved();
                writer.write(texto);
                JOptionPane.showMessageDialog(this, "Arquivo salvo com sucesso!");
            } catch (IOException ioException) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o arquivo: " + ioException.getMessage());
            }

            select = 1;
            return arquivo;
        }

        return null;
    }

    private void cancelarTelaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTelaSalvarActionPerformed
        salvar = 2;
        super.getParent().setEnabled(true);
        super.getParent().setFocusable(true);
        this.dispose();
    }//GEN-LAST:event_cancelarTelaSalvarActionPerformed

    private void naoTelaSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoTelaSalvarActionPerformed
        salvar = 1;
        super.getParent().setEnabled(true);
        super.getParent().setFocusable(true);
        this.dispose();
    }//GEN-LAST:event_naoTelaSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Salvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Salvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Salvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Salvar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarTelaSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton naoTelaSalvar;
    private javax.swing.JButton simTelaSalvar;
    private javax.swing.JLabel textoTelaSalvar;
    // End of variables declaration//GEN-END:variables
}
