/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalho_analisador_sintatico_artur_pedro_ryudi;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author Bebeto
 */
public class Terminal extends javax.swing.JFrame {

    /**
     * Creates new form Terminal
     */
    public Terminal(Tela2 pai) {
        this.initComponents();
        this.pai = pai;
        this.setTitle("Terminal");
        terminalText.setEditable(false);
        terminalText.setCaretColor(Color.GREEN);
        terminalText.setForeground(Color.GREEN);
        terminalText.setBackground(Color.BLACK);
        textoFixoSize = terminalText.getText().length();
    }

    private Tela2 pai;
    private int textoFixoSize;

    public void askInput(){
        terminalText.setNavigationFilter(new NavigationFilterPrefix(textoFixoSize,terminalText));
    }

    public void write(String str){
        terminalText.append(str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        terminalText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        terminalText.setColumns(20);
        terminalText.setLineWrap(true);
        terminalText.setRows(5);
        terminalText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                terminalTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                terminalTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                terminalTextKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(terminalText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminalTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalTextKeyPressed
        
    }//GEN-LAST:event_terminalTextKeyPressed

    private void terminalTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalTextKeyTyped
    }//GEN-LAST:event_terminalTextKeyTyped

    private void terminalTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminalTextKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            pai.setReturnTerminal(terminalText.getText().substring(textoFixoSize));
            pai.getPilhaExec().add(pai.getTopoExec()-1,pai.getReturnTerminal());
            terminalText.setEditable(false);
            pai.requestFocus();
        }
    }//GEN-LAST:event_terminalTextKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea terminalText;
    // End of variables declaration//GEN-END:variables
}